### PR TITLE
Cosmetic fix

### PR DESCRIPTION
**Pull request by Galixte**
Useless and not cosmetic.

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @lavigor,

could you merge this, please ?

**Comment by rxu** [comment]
After the fix, what it will look like?

**Comment by Galixte** [comment]
I have:
- remove a useless <br /> in the code
- change the location of the message: “Banned: Permanently” to be placed under the contact icon in mini-profile. Before this message was between profile fields of user in miniprofile and it wasn’t cosmetic.

**Comment by rxu** [comment]
OK, let's try it like that.

**Pull request merged**
